export {
  type ApiResponse,
  type Category,
  type CategoryRequest,
  type ContentManagerRequest,
  type Description,
  type DescriptionRequest,
  type FileEntry,
  type FileUploadRequest,
  type FileUploadResponse,
  type Flat,
  type FlatRequest,
  type FlatWithCategory,
  type FlatWithCategoryRequest,
  type Home,
  type HomeRequest,
  type LoginRequest,
  type PaginatedResponse,
  type PaginationParams,
  type Photo,
  type RegisterRequest,
  type RegisterResponse,
  type RequestCreate,
  type ResolvedFlat,
  type ResolvedHome,
  type SearchRequest,
  type SocialMedia,
  type UserDto,
} from '../services/api.types';



